package AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 31 18:40:02 IST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConsReportAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ConsReportAMImpl() {
    }

    /**
     * Container's getter for BusinessUnitBasedOnCont_ROVO1.
     * @return BusinessUnitBasedOnCont_ROVO1
     */
    public ViewObjectImpl getBusinessUnitBasedOnCont_ROVO1() {
        return (ViewObjectImpl)findViewObject("BusinessUnitBasedOnCont_ROVO1");
    }

    /**
     * Container's getter for businessUnitROVO1.
     * @return businessUnitROVO1
     */
    public ViewObjectImpl getbusinessUnitROVO1() {
        return (ViewObjectImpl)findViewObject("businessUnitROVO1");
    }

    /**
     * Container's getter for contractNum_SearchROVO1.
     * @return contractNum_SearchROVO1
     */
    public ViewObjectImpl getcontractNum_SearchROVO1() {
        return (ViewObjectImpl)findViewObject("contractNum_SearchROVO1");
    }

    /**
     * Container's getter for ProjectNumberROVO1.
     * @return ProjectNumberROVO1
     */
    public ViewObjectImpl getProjectNumberROVO1() {
        return (ViewObjectImpl)findViewObject("ProjectNumberROVO1");
    }

    /**
     * Container's getter for supplierROVO1.
     * @return supplierROVO1
     */
    public ViewObjectImpl getsupplierROVO1() {
        return (ViewObjectImpl)findViewObject("supplierROVO1");
    }

    /**
     * Container's getter for xxstgVendorsVO1.
     * @return xxstgVendorsVO1
     */
    public ViewObjectImpl getxxstgVendorsVO1() {
        return (ViewObjectImpl)findViewObject("xxstgVendorsVO1");
    }

    /**
     * Container's getter for supplbasedReportROVO1.
     * @return supplbasedReportROVO1
     */
    public ViewObjectImpl getsupplbasedReportROVO1() {
        return (ViewObjectImpl)findViewObject("supplbasedReportROVO1");
    }

    /**
     * Container's getter for xxstgBusinessUnitVO1.
     * @return xxstgBusinessUnitVO1
     */
    public ViewObjectImpl getxxstgBusinessUnitVO1() {
        return (ViewObjectImpl)findViewObject("xxstgBusinessUnitVO1");
    }

    /**
     * Container's getter for businessunitReportROVO1.
     * @return businessunitReportROVO1
     */
    public ViewObjectImpl getbusinessunitReportROVO1() {
        return (ViewObjectImpl)findViewObject("businessunitReportROVO1");
    }

    /**
     * Container's getter for xxscProjectNumberReportVO1.
     * @return xxscProjectNumberReportVO1
     */
    public ViewObjectImpl getxxscProjectNumberReportVO1() {
        return (ViewObjectImpl)findViewObject("xxscProjectNumberReportVO1");
    }

    /**
     * Container's getter for projectbasedReportROVO1.
     * @return projectbasedReportROVO1
     */
    public ViewObjectImpl getprojectbasedReportROVO1() {
        return (ViewObjectImpl)findViewObject("projectbasedReportROVO1");
    }

    /**
     * Container's getter for contractReportROVO1.
     * @return contractReportROVO1
     */
    public ViewObjectImpl getcontractReportROVO1() {
        return (ViewObjectImpl)findViewObject("contractReportROVO1");
    }

    /**
     * Container's getter for reportsBuLov1.
     * @return reportsBuLov1
     */
    public ViewObjectImpl getreportsBuLov1() {
        return (ViewObjectImpl)findViewObject("reportsBuLov1");
    }
}
