package AppModule;

import AppModule.common.retReleaseAM;

import oracle.adf.share.ADFContext;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 01 10:00:27 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class retReleaseAMImpl extends ApplicationModuleImpl implements retReleaseAM {
    /**
     * This is the default constructor (do not remove).
     */
    public retReleaseAMImpl() {
    }

    /**
     * Container's getter for certInvoiceROVO1.
     * @return certInvoiceROVO1
     */
    public ViewObjectImpl getcertInvoiceROVO1() {
        return (ViewObjectImpl)findViewObject("certInvoiceROVO1");
    }

    /**
     * Container's getter for XxscRetReleaseHeadersVO2_1.
     * @return XxscRetReleaseHeadersVO2_1
     */
    public ViewObjectImpl getXxscRetReleaseHeadersVO2_1() {
        return (ViewObjectImpl)findViewObject("XxscRetReleaseHeadersVO2_1");
    }

    /**
     * Container's getter for XxscRetReleaseLinesVO1.
     * @return XxscRetReleaseLinesVO1
     */
    public ViewObjectImpl getXxscRetReleaseLinesVO1() {
        return (ViewObjectImpl)findViewObject("XxscRetReleaseLinesVO1");
    }

    /**
     * Container's getter for searchRetReleaseROVO1.
     * @return searchRetReleaseROVO1
     */
    public ViewObjectImpl getsearchRetReleaseROVO1() {
        return (ViewObjectImpl)findViewObject("searchRetReleaseROVO1");
    }

    /**
     * Container's getter for RetRelLineHdrFkLink2.
     * @return RetRelLineHdrFkLink2
     */
    public ViewLinkImpl getRetRelLineHdrFkLink2() {
        return (ViewLinkImpl)findViewLink("RetRelLineHdrFkLink2");
    }

    public void refreshRetention() {
//        System.err.println("==Ret==PAGE 0==" +
//                           ADFContext.getCurrent().getSessionScope().get("page"));
        if ("add".equalsIgnoreCase((String)ADFContext.getCurrent().getSessionScope().get("addEditRet"))) {
            // Buy and sell - Create Button
            if ("retentionBuy".equalsIgnoreCase((String)ADFContext.getCurrent().getSessionScope().get("page")) ||
                "retentionSell".equalsIgnoreCase((String)ADFContext.getCurrent().getSessionScope().get("page"))) {
//                System.err.println("==Ret==PAGE ADD BUTTON==" +
//                                   ADFContext.getCurrent().getSessionScope().get("page"));
                ADFContext.getCurrent().getPageFlowScope().put("resultVal",
                                                               "NewButtonRetention");
            }
        } else if ("edit".equalsIgnoreCase((String)ADFContext.getCurrent().getSessionScope().get("addEditRet"))) {
//            System.err.println("===Ret Edit===");
            ADFContext.getCurrent().getPageFlowScope().put("resultVal",
                                                           "EditRetention");
        }

//        System.err.println("==Ret==PAGE END==" +
//                           ADFContext.getCurrent().getSessionScope().get("page"));


    }


    /**
     * Container's getter for contractLineROVO1.
     * @return contractLineROVO1
     */
    public ViewObjectImpl getcontractLineROVO1() {
        return (ViewObjectImpl)findViewObject("contractLineROVO1");
    }

    /**
     * Container's getter for XxscCertInvoices_VO1.
     * @return XxscCertInvoices_VO1
     */
    public ViewObjectImpl getXxscCertInvoices_VO1() {
        return (ViewObjectImpl)findViewObject("XxscCertInvoices_VO1");
    }
}
