package AppModule.common;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 23 17:41:56 IST 2017
// ---------------------------------------------------------------------
public interface applicationAM extends ApplicationModule {
    void refreshApplication();

    void createNewApplication();

    String deletedbcall(String p_cid, String p_type, String P_username,
                        String p_ip);

    void createVersionCal(BigDecimal contHdrId, BigDecimal appHdrId);
}
