package AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 01 11:53:11 IST 2018
// ---------------------------------------------------------------------
public interface retReleaseAM extends ApplicationModule {
    void refreshRetention();
}
