package AppModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 22 13:56:43 IST 2017
// ---------------------------------------------------------------------
public interface SellContract_AM extends ApplicationModule {
    void filterContractLineByConNum(String conNum);

    void clearHeaderLines();
}
