package AppModule.client;

import AppModule.common.applicationAM;

import java.math.BigDecimal;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Sep 23 17:41:56 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class applicationAMClient extends ApplicationModuleImpl implements applicationAM {
    /**
     * This is the default constructor (do not remove).
     */
    public applicationAMClient() {
    }


    public void refreshApplication() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshApplication",null,null);
        return;
    }

    public String deletedbcall(String p_cid, String p_type, String P_username,
                               String p_ip) {
        Object _ret =
            this.riInvokeExportedMethod(this,"deletedbcall",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {p_cid, p_type, P_username, p_ip});
        return (String)_ret;
    }

    public void createVersionCal(BigDecimal contHdrId, BigDecimal appHdrId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createVersionCal",new String [] {"java.math.BigDecimal","java.math.BigDecimal"},new Object[] {contHdrId, appHdrId});
        return;
    }

    public void createNewApplication() {
        Object _ret =
            this.riInvokeExportedMethod(this,"createNewApplication",null,null);
        return;
    }
}
