package AppModule.client;

import AppModule.common.contractAM;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 05 14:35:17 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class contractAMClient extends ApplicationModuleImpl implements contractAM {
    /**
     * This is the default constructor (do not remove).
     */
    public contractAMClient() {
    }


    public void refreshSearchScreeh() {
        Object _ret =
            this.riInvokeExportedMethod(this,"refreshSearchScreeh",null,null);
        return;
    }

    public void onClickVariation() {
        Object _ret =
            this.riInvokeExportedMethod(this,"onClickVariation",null,null);
        return;
    }

    public void contractLookup() {
        Object _ret = this.riInvokeExportedMethod(this,"contractLookup",null,null);
        return;
    }

    public void totalContractSum(String headId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"totalContractSum",new String [] {"java.lang.String"},new Object[] {headId});
        return;
    }

    public void usercount() {
        Object _ret = this.riInvokeExportedMethod(this,"usercount",null,null);
        return;
    }

    public String deletedbcall(String p_cid, String p_type, String P_username,
                               String p_ip) {
        Object _ret =
            this.riInvokeExportedMethod(this,"deletedbcall",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {p_cid, p_type, P_username, p_ip});
        return (String)_ret;
    }
}
