package view;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 23 14:26:21 IST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxscContractGuaranteeVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ContGuarId {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getContGuarId();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setContGuarId((Number)value);
            }
        }
        ,
        ContHeaderId {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getContHeaderId();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setContHeaderId((Number)value);
            }
        }
        ,
        DataSetId {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getDataSetId();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setDataSetId((Number)value);
            }
        }
        ,
        GuarCategory {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getGuarCategory();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setGuarCategory((String)value);
            }
        }
        ,
        GuarType {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getGuarType();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setGuarType((String)value);
            }
        }
        ,
        Institution {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getInstitution();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setInstitution((String)value);
            }
        }
        ,
        StartDate {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getStartDate();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setStartDate((Date)value);
            }
        }
        ,
        EndDate {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getEndDate();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setEndDate((Date)value);
            }
        }
        ,
        Duration {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getDuration();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setDuration((String)value);
            }
        }
        ,
        Value {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getValue();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setValue((Number)value);
            }
        }
        ,
        RefNumber {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getRefNumber();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setRefNumber((String)value);
            }
        }
        ,
        Remarks {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        OrgId {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ObjectVersionNumber {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getObjectVersionNumber();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setObjectVersionNumber((Number)value);
            }
        }
        ,
        AttributeCategory {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttributeCategory();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeCategory((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setCreationDate((Timestamp)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((String)value);
            }
        }
        ,
        Version {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getVersion();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setVersion((Number)value);
            }
        }
        ,
        VersionType {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getVersionType();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setVersionType((String)value);
            }
        }
        ,
        TransFileName {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getTransFileName();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setTransFileName((String)value);
            }
        }
        ,
        FileType {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getFileType();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setFileType((String)value);
            }
        }
        ,
        FileName {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getFileName();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setFileName((String)value);
            }
        }
        ,
        Attachment {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getAttachment();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttachment((BlobDomain)value);
            }
        }
        ,
        XxscContractHeadersVO {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getXxscContractHeadersVO();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XxscAttachmentVO {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getXxscAttachmentVO();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        gaurCat_VA {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getgaurCat_VA();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        gaurType_VA {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getgaurType_VA();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Notification1 {
            public Object get(XxscContractGuaranteeVORowImpl obj) {
                return obj.getNotification1();
            }

            public void put(XxscContractGuaranteeVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(XxscContractGuaranteeVORowImpl object);

        public abstract void put(XxscContractGuaranteeVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CONTGUARID = AttributesEnum.ContGuarId.index();
    public static final int CONTHEADERID = AttributesEnum.ContHeaderId.index();
    public static final int DATASETID = AttributesEnum.DataSetId.index();
    public static final int GUARCATEGORY = AttributesEnum.GuarCategory.index();
    public static final int GUARTYPE = AttributesEnum.GuarType.index();
    public static final int INSTITUTION = AttributesEnum.Institution.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int DURATION = AttributesEnum.Duration.index();
    public static final int VALUE = AttributesEnum.Value.index();
    public static final int REFNUMBER = AttributesEnum.RefNumber.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int OBJECTVERSIONNUMBER = AttributesEnum.ObjectVersionNumber.index();
    public static final int ATTRIBUTECATEGORY = AttributesEnum.AttributeCategory.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int VERSIONTYPE = AttributesEnum.VersionType.index();
    public static final int TRANSFILENAME = AttributesEnum.TransFileName.index();
    public static final int FILETYPE = AttributesEnum.FileType.index();
    public static final int FILENAME = AttributesEnum.FileName.index();
    public static final int ATTACHMENT = AttributesEnum.Attachment.index();
    public static final int XXSCCONTRACTHEADERSVO = AttributesEnum.XxscContractHeadersVO.index();
    public static final int XXSCATTACHMENTVO = AttributesEnum.XxscAttachmentVO.index();
    public static final int GAURCAT_VA = AttributesEnum.gaurCat_VA.index();
    public static final int GAURTYPE_VA = AttributesEnum.gaurType_VA.index();
    public static final int NOTIFICATION1 = AttributesEnum.Notification1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxscContractGuaranteeVORowImpl() {
    }

    /**
     * Gets XxscContractGuaranteeEO entity object.
     * @return the XxscContractGuaranteeEO
     */
    public EntityImpl getXxscContractGuaranteeEO() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for CONT_GUAR_ID using the alias name ContGuarId.
     * @return the CONT_GUAR_ID
     */
    public Number getContGuarId() {
        return (Number)getAttributeInternal(CONTGUARID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_GUAR_ID using the alias name ContGuarId.
     * @param value value to set the CONT_GUAR_ID
     */
    public void setContGuarId(Number value) {
        setAttributeInternal(CONTGUARID, value);
    }

    /**
     * Gets the attribute value for CONT_HEADER_ID using the alias name ContHeaderId.
     * @return the CONT_HEADER_ID
     */
    public Number getContHeaderId() {
        return (Number)getAttributeInternal(CONTHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for CONT_HEADER_ID using the alias name ContHeaderId.
     * @param value value to set the CONT_HEADER_ID
     */
    public void setContHeaderId(Number value) {
        setAttributeInternal(CONTHEADERID, value);
    }

    /**
     * Gets the attribute value for DATA_SET_ID using the alias name DataSetId.
     * @return the DATA_SET_ID
     */
    public Number getDataSetId() {
        return (Number)getAttributeInternal(DATASETID);
    }

    /**
     * Sets <code>value</code> as attribute value for DATA_SET_ID using the alias name DataSetId.
     * @param value value to set the DATA_SET_ID
     */
    public void setDataSetId(Number value) {
        setAttributeInternal(DATASETID, value);
    }

    /**
     * Gets the attribute value for GUAR_CATEGORY using the alias name GuarCategory.
     * @return the GUAR_CATEGORY
     */
    public String getGuarCategory() {
        return (String) getAttributeInternal(GUARCATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for GUAR_CATEGORY using the alias name GuarCategory.
     * @param value value to set the GUAR_CATEGORY
     */
    public void setGuarCategory(String value) {
        setAttributeInternal(GUARCATEGORY, value);
    }

    /**
     * Gets the attribute value for GUAR_TYPE using the alias name GuarType.
     * @return the GUAR_TYPE
     */
    public String getGuarType() {
        return (String) getAttributeInternal(GUARTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for GUAR_TYPE using the alias name GuarType.
     * @param value value to set the GUAR_TYPE
     */
    public void setGuarType(String value) {
        setAttributeInternal(GUARTYPE, value);
    }

    /**
     * Gets the attribute value for INSTITUTION using the alias name Institution.
     * @return the INSTITUTION
     */
    public String getInstitution() {
        return (String) getAttributeInternal(INSTITUTION);
    }

    /**
     * Sets <code>value</code> as attribute value for INSTITUTION using the alias name Institution.
     * @param value value to set the INSTITUTION
     */
    public void setInstitution(String value) {
        setAttributeInternal(INSTITUTION, value);
    }

    /**
     * Gets the attribute value for START_DATE using the alias name StartDate.
     * @return the START_DATE
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate.
     * @param value value to set the START_DATE
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for END_DATE using the alias name EndDate.
     * @return the END_DATE
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate.
     * @param value value to set the END_DATE
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for DURATION using the alias name Duration.
     * @return the DURATION
     */
    public String getDuration() {
        return (String) getAttributeInternal(DURATION);
    }

    /**
     * Sets <code>value</code> as attribute value for DURATION using the alias name Duration.
     * @param value value to set the DURATION
     */
    public void setDuration(String value) {
        setAttributeInternal(DURATION, value);
    }

    /**
     * Gets the attribute value for VALUE using the alias name Value.
     * @return the VALUE
     */
    public Number getValue() {
        return (Number)getAttributeInternal(VALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE using the alias name Value.
     * @param value value to set the VALUE
     */
    public void setValue(Number value) {
        setAttributeInternal(VALUE, value);
    }

    /**
     * Gets the attribute value for REF_NUMBER using the alias name RefNumber.
     * @return the REF_NUMBER
     */
    public String getRefNumber() {
        return (String) getAttributeInternal(REFNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_NUMBER using the alias name RefNumber.
     * @param value value to set the REF_NUMBER
     */
    public void setRefNumber(String value) {
        setAttributeInternal(REFNUMBER, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @return the OBJECT_VERSION_NUMBER
     */
    public Number getObjectVersionNumber() {
        return (Number)getAttributeInternal(OBJECTVERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for OBJECT_VERSION_NUMBER using the alias name ObjectVersionNumber.
     * @param value value to set the OBJECT_VERSION_NUMBER
     */
    public void setObjectVersionNumber(Number value) {
        setAttributeInternal(OBJECTVERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @return the ATTRIBUTE_CATEGORY
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE_CATEGORY using the alias name AttributeCategory.
     * @param value value to set the ATTRIBUTE_CATEGORY
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public String getCreatedBy() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Timestamp value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public String getLastUpdatedBy() {
        return (String) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(String value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public String getLastUpdateLogin() {
        return (String) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(String value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public Number getVersion() {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(Number value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for VERSION_TYPE using the alias name VersionType.
     * @return the VERSION_TYPE
     */
    public String getVersionType() {
        return (String) getAttributeInternal(VERSIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_TYPE using the alias name VersionType.
     * @param value value to set the VERSION_TYPE
     */
    public void setVersionType(String value) {
        setAttributeInternal(VERSIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransFileName.
     * @return the TransFileName
     */
    public String getTransFileName() {
        return (String) getAttributeInternal(TRANSFILENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransFileName.
     * @param value value to set the  TransFileName
     */
    public void setTransFileName(String value) {
        setAttributeInternal(TRANSFILENAME, value);
    }

    /**
     * Gets the attribute value for FILE_TYPE using the alias name FileType.
     * @return the FILE_TYPE
     */
    public String getFileType() {
        return (String) getAttributeInternal(FILETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_TYPE using the alias name FileType.
     * @param value value to set the FILE_TYPE
     */
    public void setFileType(String value) {
        setAttributeInternal(FILETYPE, value);
    }

    /**
     * Gets the attribute value for FILE_NAME using the alias name FileName.
     * @return the FILE_NAME
     */
    public String getFileName() {
        return (String) getAttributeInternal(FILENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FILE_NAME using the alias name FileName.
     * @param value value to set the FILE_NAME
     */
    public void setFileName(String value) {
        setAttributeInternal(FILENAME, value);
    }

    /**
     * Gets the attribute value for ATTACHMENT using the alias name Attachment.
     * @return the ATTACHMENT
     */
    public BlobDomain getAttachment() {
        return (BlobDomain)getAttributeInternal(ATTACHMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACHMENT using the alias name Attachment.
     * @param value value to set the ATTACHMENT
     */
    public void setAttachment(BlobDomain value) {
        setAttributeInternal(ATTACHMENT, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link XxscContractHeadersVO.
     */
    public Row getXxscContractHeadersVO() {
        return (Row)getAttributeInternal(XXSCCONTRACTHEADERSVO);
    }

    /**
     * Sets the master-detail link XxscContractHeadersVO between this object and <code>value</code>.
     */
    public void setXxscContractHeadersVO(Row value) {
        setAttributeInternal(XXSCCONTRACTHEADERSVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XxscAttachmentVO.
     */
    public RowIterator getXxscAttachmentVO() {
        return (RowIterator)getAttributeInternal(XXSCATTACHMENTVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> gaurCat_VA.
     */
    public RowSet getgaurCat_VA() {
        return (RowSet)getAttributeInternal(GAURCAT_VA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> gaurType_VA.
     */
    public RowSet getgaurType_VA() {
        return (RowSet)getAttributeInternal(GAURTYPE_VA);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Notification1.
     */
    public RowSet getNotification1() {
        return (RowSet)getAttributeInternal(NOTIFICATION1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
