package view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jan 02 17:48:46 IST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxscContractHeadersVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XxscContractHeadersVOImpl() {
    }


    /**
     * Returns the variable value for BV_ID.
     * @return variable value for BV_ID
     */
    public String getBV_ID() {
        return (String)ensureVariableManager().getVariableValue("BV_ID");
    }

    /**
     * Sets <code>value</code> for variable BV_ID.
     * @param value value to bind as BV_ID
     */
    public void setBV_ID(String value) {
        ensureVariableManager().setVariableValue("BV_ID", value);
    }

    /**
     * Returns the variable value for BV_VER.
     * @return variable value for BV_VER
     */
    public String getBV_VER() {
        return (String)ensureVariableManager().getVariableValue("BV_VER");
    }

    /**
     * Sets <code>value</code> for variable BV_VER.
     * @param value value to bind as BV_VER
     */
    public void setBV_VER(String value) {
        ensureVariableManager().setVariableValue("BV_VER", value);
    }

    /**
     * Returns the bind variable value for BV_ProjectNum.
     * @return bind variable value for BV_ProjectNum
     */
    public String getBV_ProjectNum() {
        return (String)getNamedWhereClauseParam("BV_ProjectNum");
    }

    /**
     * Sets <code>value</code> for bind variable BV_ProjectNum.
     * @param value value to bind as BV_ProjectNum
     */
    public void setBV_ProjectNum(String value) {
        setNamedWhereClauseParam("BV_ProjectNum", value);
    }
}
